name: jupyter-book-pages

on:
  push:
    brances:
      - main
  workflow_dispatch:

jobs:
  build_book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: build the book
        run: |
          python3 -m pip install -r requirements.txt
          jupyter-book build pages
      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
  # Deploy the book's HTML to GitHub Pages
  deploy_book:
    needs: build_book
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
    runs-on: ubuntu-latest
    steps:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "pages/_build/html"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4